erDiagram
    PRICES {
        int id
        string itemName
        decimal price
    }

    ORDER {
        int id
        timestamp orderDate
        int javaQuantity
        int javaDrinkType
        decimal javaSubtotal
        int cafeQuantity
        int cafeDrinkType
        decimal cafeSubtotal
        int cappQuantity
        int cappDrinkType
        decimal cappSubtotal
        decimal totalPrice

    }
